### ISSUE TITLE
Setup tink globally?

### ISSUE THREAD

**Issue by fullofcaffeine** [haxetink/tink_lang#12]
Hey Juraj! Greetings!

Any ways to summon the tink awesomeness not on a per class basis, but globally?

**Comment by back2dos** [comment]
Since it's all just a matter of setting the `@:tink` metadata, you can use [Compiler.addGlobalMetadata](http://api.haxe.org/haxe/macro/Compiler.html#addGlobalMetadata), e.g. compile with `--macro addGlobalMetadata("", "@:tink")`. Note that this will also apply tink_lang to the whole standard library. That will take ages and I'm not even sure it will work correctly. Restricting yourself to something like `--macro addGlobalMetadata("your_package", "@:tink")` should be a good middle ground.

**Comment by fullofcaffeine** [comment]
Thanks for the comprehensive answer, I'll try it out.
