### ISSUE TITLE
Static partial implementation

### ISSUE THREAD

**Issue by deathbeam** [haxetink/tink_lang#20]
So hello again. I am trying to use tink_lang to do some mixin-things, and first thing I noticed is that it does not support partial implementation of static fields. I would expect that this will work:

``` haxe
@:tink interface Mixin {
  public static function hello() : Void {
    trace("Hello World");
  }
}
```

So I will be able to for example do this with above:

``` haxe
@:tink class Main implements Mixin {
  public static function main() {
    hello();
  }
}
```

**Comment by back2dos** [comment]
The whole notion of implementation - i.e. a class implementing an interface - revolves around the instances and not the class objects, so it never occurred to me that one might want to do this. I'll have to think about this.

**Comment by deathbeam** [comment]
For functional programming it can be really awesome thing to have.

**Comment by back2dos** [comment]
Could you provide an example of that?

**Comment by deathbeam** [comment]
Below is really primitive sample, but I think it explains the usage very well.

``` haxe
// Below things will partially solve our issue, but they would need to be
// in different module to enable this.
// Also, even if they will be in another module, it will not restrict their usage
// and we will be able to use them in all our classes below
import Addition.*;
import Division.*;

@:tink class Main implements Addition implements Division {
  public static function main() {
    // We want to only use addition here
    trace(add(5 , 5));
  }
}

@:tink class Other {
  public static function main() {
    // We do not want to use our math operations here
    trace("Nothing");
  }
}

@:tink class Other2 implements Division {
  public static function main() {
    // We want to use only division here
    trace(div(10, 2));
  }
}

@:tink interface Addition {
  static function add(a, b) return a + b;
  static function sub(a, b) return a - b;
}

@:tink interface Division {
  static function div(a, b) return a / b;
  static function mult(a, b) return a * b;
}
```

**Comment by back2dos** [comment]
Ok, well first of all, you don't have to put things into different modules, but you have to import module subtypes by their full path. Example: http://try.haxe.org/#Dc4ec

Personally though, I find [static extensions](http://try.haxe.org/#A0A9D) far more appealing, because it actually dispatches on the compile time type, meaning that you can have two different functions for adding vectors and adding floats without any conflicts.

In Haxe, inheritance does not work on class objects: http://try.haxe.org/#b2a86
It would therefore be weird to support it on partial implementation.

What I think might be sensible would be to support [syntactic delegation](https://github.com/haxetink/tink_lang#syntactic-delegation) on static members. It would then look something like this:

```
@:tink class Main {
  @:forward static var addition = new Addition();
  public static function main() 
    trace(add(5 , 5));
}

class Addition {
  public function new() {}
  public inline function add<N:Float>(a:N, b:N):N return a + b;
}
```

Would that address your use cases?

**Comment by deathbeam** [comment]
Yes, I know that you cannot inherit static fields from another class in Haxe, but for example in Java, you can implement static fields from interfaces. Example:

``` java
interface CarConstants {
      static final String ENGINE = "mechanical";
      static final String WHEEL  = "round";
}
```

But syntactic delegation on static members sound great too.

**Comment by fullofcaffeine** [comment]
Any news here? I stumbled upon a problem that would benefit from including static members of another class (acting as a module) into another.

**Comment by back2dos** [comment]
Hmm. A simpler solution for the presented use cases is is to rely on `import SomeClass.*` to get all the static members into scope. Feel free to open a new issue with a use case not adequately covered by that.
