### ISSUE TITLE
@:readOnly no work on hl target

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_lang#36]
@:tink 
	class Main {
		static function main() {
		
			var m=new Main();
			m.x=2;//can compile
			trace(m.x);

		}

		@:readOnly public var x:Int=1;
		public function new() {
			
		}
	}

**Comment by back2dos** [comment]
That's a typo. It should be `@:readonly`, not `@:readOnly` ;)

**Comment by sonygod** [comment]
@:tink
    class Main {
        static function main() {
            var m = new Main();
            m.x = 2;

            trace(m.x);
        }

        @:readonly public var x:Int = 1;

        public function new() {}
    }


same result as before .

        D:\project\testxxx>build.hxml

        D:\project\testxxx>hl test.hl
        src/Main.hx:10: 2

        D:\project\testxxx>

@back2dos

**Comment by back2dos** [comment]
Yeah. That's because you're accessing the variable from within the same class, which is allowed for read only variables. The compiler error only occurs when [attempting write access from another class](https://try.haxe.org/#21D78):

```haxe
class Test {
    static function main() {
        var m = new Foo();
        m.x = 2;

        trace(m.x);
    }

}

@:tink class Foo {
    @:readonly public var x:Int = 1;

    public function new() {}    
}
```

If you want a field that cannot be written to even from the class itself, consider using `final` instead ;)
